commit-msg:
  commands:
    cog:
      run: cog verify --ignore-merge-commits --file {1}

pre-commit:
  commands:
    lint:
      run: moon :lint

pre-push:
  commands:
    cog:
      run: cog check --ignore-merge-commits
